In [58]:
import pandas as pd

df = pd.read_csv("NP.csv")


#filter only National parks & get unique years

np_df = df.loc[(df["Unit Type"] == "National Park")]
np_df = np_df[np_df['State'] != 'HI']
np_df = np_df[np_df['State'] != 'AK']
df_names = np_df['Unit Name'].unique()
year_df = np_df['YearRaw'].unique()

#pseudo code for restructuring

new_df = pd.DataFrame(index=df_names, columns=year_df).fillna("0")
#for every name in names:
    #for every year in years:
        #make new column in names df
            #add value (0 or value) for each park name and year


# Iterate through each row in np_df and update the corresponding cell in new_df
for i, row in np_df.iterrows():
    park = row['Unit Name']
    year = row['YearRaw']
    string = row[" Visitors "].strip()
    visitors = string.replace(",", "")
    new_df.at[park, year] = visitors


new_df = new_df.reset_index()

new_df.to_json('output.json', orient='records', lines=True)
#new_df.to_csv("output.csv")

In [88]:
# clean national park data:

mf_df = pd.read_csv("np.csv")
np_df = df.loc[(df["Unit Type"] == "National Park")]
np_df = np_df.drop(columns=['Unit Type', 'Unit Code'])
np_df.replace({'\$': '', ',': ''}, regex=True, inplace=True)

np_df

acronyms = pd.read_csv("names.csv")

state_mapping = acronyms.set_index('Postal')['State'].to_dict()

# Use the map function to replace state acronyms with full state names in df1
np_df['State'] = np_df['State'].map(state_mapping)

np_df
#np_df.to_csv("npdata.csv")

set = np_df['State'].unique()
print("the number of unique states is: ", len(set))

the number of unique states is:  27

In [69]:
#print to see
gdp_df = pd.read_csv("GDP.csv")
gdp_df.replace({'\$': '', ',': ''}, regex=True, inplace=True)
gdp_df.rename(columns=lambda x: x.replace('$', '').replace(',', '').replace(' ', ''), inplace=True)
gdp_df
#gdp_df.to_json('clean_gdp.json', orient='records', lines=True)
gdp_df.to_csv('clean_data.csv')
gdp_df

                   State       2000       2005       2010       2015
0          United States  10219801   13015161   14859772   17919651
1                Alabama    119020     156750     174710     199656
2                 Alaska     26853      40063      54134      52747
3                Arizona    165912     227358     245668     290903
4               Arkansas     68809      90319     102951     118907
5             California   1362995    1766693    1965886    2481348
6               Colorado    181488     220454     253374     313748
7            Connecticut    169004     210170     234528     252930
8               Delaware     44851      53247      57471      68724
9   District of Columbia     60059      83586     103831     122146
10               Florida    497541     700267     735098     888087
11               Georgia    306528     388342     412485     497944
12                Hawaii     41472      58573      68225      80376
13                 Idaho     38216      47176      55258      65549
14              Illinois    491644     586442     653476     776882
15               Indiana    205487     245197     282259     336053
16                  Iowa     94792     123353     141697     174030
17                Kansas     86869     104884     128542     149641
18              Kentucky    114592     143875     165974     193274
19             Louisiana    133200     199683     232596     239305
20                 Maine     37072      46277      51456      57297
21              Maryland    192565     263809     313952     365356
22         Massachusetts    289688     345059     402652     484943
23              Michigan    351621     395166     385021     468334
24             Minnesota    191106     243933     269937     328340
25           Mississippi     65937      81678      95810     105819
26              Missouri    188736     224091     255865     294491
27               Montana     21953      30637      38375      45237
28              Nebraska     57235      73455      92231     113282
29                Nevada     77006     118785     121713     139724
30         New Hampshire     45519      57282      64159      73867
31            New Jersey    363295     443148     489130     567738
32            New Mexico     55255      74403      86079      93339
33              New York    833306    1023433    1204688    1433531
34        North Carolina    277141     357168     416008     495402
35          North Dakota     17973      24622      36202      55860
36                  Ohio    395127     467392     498989     610928
37              Oklahoma     91421     125243     149913     185981
38                Oregon    117557     147535     191120     217629
39          Pennsylvania    408556     506505     596662     709762
40          Rhode Island     34613      45663      49351      56052
41        South Carolina    115809     143585     164106     201005
42          South Dakota     22875      31380      38176      47244
43             Tennessee    181216     227505     252478     315857
44                 Texas    741115     990054    1243398    1630082
45                  Utah     70172      94475     117714     147503
46               Vermont     18391      23539      26633      30038
47              Virginia    268371     359273     420862     481084
48            Washington    237381     296403     359694     445413
49         West Virginia     42703      53453      67255      74321
50             Wisconsin    182408     226325     252875     302076
51               Wyoming     17349      27454      39103      39864

In [49]:
new_json = pd.read_json("output.json", lines=True)
new_json

,index,Total,2016,2015,2014,2013,2012,2011,2010,2009,...,1913,1912,1911,1910,1909,1908,1907,1906,1905,1904
0,Great Smoky Mountains National Park,"521,947,058","11,312,786","10,712,674","10,099,276","9,354,695","9,685,829","9,008,830","9,463,538","9,491,437",...,0,0,0,0,0,0,0,0,0,0
1,Grand Canyon National Park,"205,486,894","5,969,811","5,520,736","4,756,771","4,564,840","4,421,352","4,298,178","4,388,386","4,348,068",...,0,0,0,0,0,0,0,0,0,0
2,Yosemite National Park,"190,404,561","5,028,868","4,150,217","3,882,642","3,691,191","3,853,404","3,951,393","3,901,408","3,737,472",...,"13,735","10,884","12,530","13,619","13,182","8,850","7,102","5,414",0,0
3,Rocky Mountain National Park,"180,076,609","4,517,585","4,155,916","3,434,751","2,991,141","3,229,617","3,176,941","2,955,821","2,822,325",...,0,0,0,0,0,0,0,0,0,0
4,Yellowstone National Park,"175,040,126","4,257,177","4,097,710","3,513,484","3,188,030","3,447,729","3,394,326","3,640,185","3,295,187",...,"24,929","22,970","23,054","19,575","32,545","19,542","16,414","17,182","26,188","13,727"
5,Acadia National Park,"163,512,192","3,303,393","2,811,184","2,563,129","2,254,922","2,431,052","2,374,645","2,504,208","2,227,698",...,0,0,0,0,0,0,0,0,0,0
6,Olympic National Park,"160,737,962","3,390,221","3,263,761","3,243,872","3,085,340","2,824,908","2,966,502","2,844,563","3,276,459",...,0,0,0,0,0,0,0,0,0,0
7,Grand Teton National Park,"147,898,402","3,270,076","3,149,921","2,791,392","2,688,794","2,705,256","2,587,437","2,669,374","2,580,081",...,0,0,0,0,0,0,0,0,0,0
8,Shenandoah National Park,"126,112,145","1,437,341","1,321,873","1,255,321","1,136,505","1,210,200","1,209,883","1,253,386","1,120,981",...,0,0,0,0,0,0,0,0,0,0
9,Zion National Park,"111,311,078","4,295,127","3,648,846","3,189,696","2,807,387","2,973,607","2,825,505","2,665,972","2,735,402",...,0,0,0,0,0,0,0,0,0,0
10,Glacier National Park,"105,029,559","2,946,681","2,366,056","2,338,528","2,190,374","2,162,035","1,853,564","2,200,048","2,031,348",...,"12,138","6,257","4,000",0,0,0,0,0,0,0
11,Mount Rainier National Park,"94,488,801","1,356,913","1,237,231","1,264,259","1,148,552","1,049,178","1,038,229","1,191,754","1,151,654",...,"13,501","8,946","10,306","8,000","5,968","2,826","2,068","1,786",928,563
12,Hot Springs National Park,"92,028,933","1,544,300","1,418,162","1,424,484","1,325,719","1,302,505","1,396,354","1,311,807","1,284,707",...,"135,000","135,000","130,000","120,000",0,0,0,0,"109,000","101,000"
13,Mammoth Cave National Park,"84,750,237","586,514","566,895","522,628","494,541","508,054","483,319","497,225","503,856",...,0,0,0,0,0,0,0,0,0,0
14,Cuyahoga Valley National Park,"81,631,077","2,423,390","2,284,612","2,189,849","2,103,010","2,299,722","2,161,185","2,492,670","2,589,288",...,0,0,0,0,0,0,0,0,0,0
15,Badlands National Park,"69,483,454","996,263","989,354","868,094","892,372","883,406","870,741","977,778","933,918",...,0,0,0,0,0,0,0,0,0,0
16,Sequoia National Park,"62,857,221","1,254,688","1,097,464","1,039,137","909,274","1,106,584","1,006,583","1,002,979","965,170",...,"3,823","2,923","3,114","2,407",854,"1,251",900,700,0,0
17,Joshua Tree National Park,"56,684,694","2,505,286","2,025,756","1,589,904","1,383,340","1,396,117","1,396,237","1,434,976","1,304,471",...,0,0,0,0,0,0,0,0,0,0
18,Everglades National Park,"56,228,594","930,907","1,077,427","1,110,901","1,047,116","1,141,906","934,351","915,538","900,882",...,0,0,0,0,0,0,0,0,0,0
19,Petrified Forest National Park,"54,138,794","643,274","793,225","836,799","644,648","664,857","614,054","664,725","631,613",...,0,0,0,0,0,0,0,0,0,0
20,Kings Canyon National Park,"52,978,184","607,479","468,106","502,268","567,544","591,033","566,810","598,205","609,296",...,"2,756","2,240","2,160","1,178",798,"1,773","1,100",900,"1,000","1,000"
21,Bryce Canyon National Park,"49,710,389","2,365,110","1,745,804","1,435,741","1,311,875","1,385,352","1,296,000","1,285,492","1,216,377",...,0,0,0,0,0,0,0,0,0,0
22,Death Valley National Park,"46,007,802","1,296,283","1,154,843","1,101,312","951,972","984,568","946,867","984,775","828,574",...,0,0,0,0,0,0,0,0,0,0
23,Carlsbad Caverns National Park,"43,733,704","466,773","445,720","397,309","388,566","381,058","365,000","428,524","432,639",...,0,0,0,0,0,0,0,0,0,0
24,Wind Cave National Park,"41,035,166","617,377","612,198","547,022","516,142","529,083","538,394","577,141","587,868",...,"3,988","3,199","3,887","3,387","3,216","3,171","2,751","2,787","2,438","2,900"
25,Crater Lake National Park,"34,669,486","756,344","614,712","535,508","523,027","447,251","423,551","448,319","446,516",...,"6,253","5,235","4,500","5,000","4,171","5,275","2,600","1,800","1,400","1,500"
26,Saguaro National Park,"33,169,763","820,426","753,446","673,572","678,261","634,286","610,045","717,614","665,234",...,0,0,0,0,0,0,0,0,0,0
27,Mesa Verde National Park,"32,863,857","583,527","547,325","501,563","460,237","488,860","572,329","559,712","550,377",...,280,230,206,250,165,80,0,0,0,0
28,Arches National Park,"32,577,956","1,585,718","1,399,247","1,284,767","1,082,866","1,070,577","1,040,758","1,014,405","996,312",...,0,0,0,0,0,0,0,0,0,0
29,Theodore Roosevelt National Park,"31,479,563","753,880","580,033","559,580","545,090","640,555","563,407","623,748","586,928",...,0,0,0,0,0,0,0,0,0,0
30,Lassen Volcanic National Park,"28,290,902","536,068","468,092","432,977","427,409","407,653","351,269","384,570","365,639",...,0,0,0,0,0,0,0,0,0,0
31,Virgin Islands National Park,"25,980,135","411,343","438,372","426,930","438,601","483,341","442,414","493,477","415,847",...,0,0,0,0,0,0,0,0,0,0
32,Capitol Reef National Park,"25,845,196","1,064,904","941,029","786,514","663,670","673,345","668,834","662,661","617,208",...,0,0,0,0,0,0,0,0,0,0
33,Wolf Trap National Park for the Performing Arts,"23,496,183","437,513","407,351","388,283","441,166","426,996","425,177","520,397","466,752",...,0,0,0,0,0,0,0,0,0,0
34,Redwood National Park,"19,353,209","536,297","527,143","429,166","393,364","352,517","380,167","418,820","444,426",...,0,0,0,0,0,0,0,0,0,0
35,Biscayne National Park,"18,615,078","514,709","508,164","525,745","486,848","495,613","476,077","467,612","437,745",...,0,0,0,0,0,0,0,0,0,0
36,Big Bend National Park,"15,820,237","388,290","381,747","314,102","316,953","292,055","361,862","372,330","363,905",...,0,0,0,0,0,0,0,0,0,0
37,North Cascades National Park,"14,809,679","28,646","20,677","23,865","21,623","26,935","19,208","24,659","26,972",...,0,0,0,0,0,0,0,0,0,0
38,Canyonlands National Park,"13,990,095","776,218","634,607","542,431","462,242","452,952","473,773","435,908","436,241",...,0,0,0,0,0,0,0,0,0,0
39,Black Canyon of the Gunnison National Park,"13,686,363","238,018","209,166","183,045","175,852","192,570","168,336","176,344","171,451",...,0,0,0,0,0,0,0,0,0,0
40,Great Sand Dunes National Park,"13,526,909","388,308","299,513","271,774","242,841","254,674","280,058","283,284","289,955",...,0,0,0,0,0,0,0,0,0,0
41,Channel Islands National Park,"12,352,355","364,807","324,816","342,161","212,029","249,594","242,756","277,515","348,745",...,0,0,0,0,0,0,0,0,0,0
42,Pinnacles National Park,"10,492,968","215,555","206,533","196,635","237,677","224,476","393,219","246,575","171,112",...,0,0,0,0,0,0,0,0,0,0
43,Voyageurs National Park,"8,861,822","241,912","238,313","239,160","233,390","214,841","177,184","253,891","222,429",...,0,0,0,0,0,0,0,0,0,0
44,Guadalupe Mountains National Park,"7,211,673","181,839","169,535","166,868","145,670","159,360","152,546","192,210","198,882",...,0,0,0,0,0,0,0,0,0,0
45,Great Basin National Park,"3,770,774","144,846","116,123","107,526","92,893","94,850","91,451","88,870","84,974",...,0,0,0,0,0,0,0,0,0,0
46,Congaree National Park,"2,629,690","143,843","87,513","120,122","120,340","109,685","120,166","121,208","122,970",...,0,0,0,0,0,0,0,0,0,0
47,Dry Tortugas National Park,"2,004,566","73,661","70,862","64,865","58,401","60,550","75,171","53,890","52,011",...,0,0,0,0,0,0,0,0,0,0
48,Isle Royale National Park,"1,071,614","24,966","18,684","14,560","16,274","16,663","15,892","15,793","14,653",...,0,0,0,0,0,0,0,0,0,0
49,National Park of American Samoa,"113,694","28,892","13,892","13,953","17,919","10,440","8,716","3,006","3,242",...,0,0,0,0,0,0,0,0,0,0